module.exports = {
    Meta: {
        title: 'Hauknetz API',
        version: '1.0.0',
        Auhtor: 'Vecto. (Tim Hauke), Hauknetz',
        description: 'Die vollwertige Hauknetz API die wir zuletzt genutzt haben.',
        contact: {
            name: 'Hauknetz',
            url: 'https://hauknetz.de',
            email: 'info@hauknetz.de',
        },
        license: {
            name: 'MIT',
            url: 'https://opensource.org/licenses/MIT',
        },
    },
    Errors: {
        general: 'An error occurred',
        notFound: 'The requested resource was not found',
        unauthorized: 'You are not authorized to access this resource',
        forbidden: 'You are forbidden to perform this action',
        conflict: 'A conflict occurred',
        unprocessableEntity: 'The request could not be processed due to validation errors',
        tooManyRequests: 'Too many requests have been made to the server',
        internalServerError: 'An internal server error occurred',
        serviceUnavailable: 'The server is temporarily unavailable',
    },
    Success: {
        created: 'The resource has been created successfully',
        updated: 'The resource has been updated successfully',
        deleted: 'The resource has been deleted successfully',
        retrieved: 'The resource has been retrieved successfully',
        sent: 'The email has been sent successfully',
        queued: 'The job has been queued successfully',
        processed: 'The job has been processed successfully',
        triggered: 'The event has been triggered successfully',
        set: 'The setting has been set successfully',
        reset: 'The password has been reset successfully',
        loggedIn: 'You have successfully logged in',
        loggedOut: 'You have successfully logged out',
        verified: 'Your email address has been verified successfully',
        resentVerificationEmail: 'A verification email has been sent to your email address',
        disabled: 'The user account has been disabled successfully',
        enabled: 'The user account has been enabled successfully',
        joined: 'You have joined the organization successfully',
        left: 'You have left the organization successfully'
    },
    Validation: {
        required: '{field} is required',
        email: '{field} must be a valid email address',
        password: '{field} must be at least 8 characters long and contain at least one uppercase letter, one lowercase letter, one number, and one special character',
        confirmPassword: '{field} and {confirmField} must match',
        unique: '{field} must be unique',
        minLength: '{field} must be at least {length} characters long',
        maxLength: '{field} must be no more than {length} characters long',
        min: '{field} must be at least {min}',
        max: '{field} must be no more than {max}',
        pattern: '{field} must match the pattern {pattern}',
        inArray: '{field} must be one of the following: {values}',
        notInArray: '{field} cannot be one of the following: {values}',
        exists: '{field} does not exist'
    },
    Auth: {
        login: 'Login successful',
        logout: 'Logout successful',
        register: 'Registration successful',
        verifyEmail: 'Email verification successful',
        resetPassword: 'Password reset successful',
        forgotPassword: 'Password reset link sent to your email address',
        changePassword: 'Password changed successfully',
        sendVerificationEmail: 'Verification email sent to your email address',
        updateProfile: 'Profile updated successfully',
        updateSettings: 'Settings updated successfully',
        updateEmail: 'Email address updated successfully',
        updatePassword: 'Password updated successfully',
        deleteAccount: 'Account deleted successfully',
        resendVerificationEmail: 'Verification email resent to your email address',
        disableAccount: 'Account disabled successfully',
        enableAccount: 'Account enabled successfully',
        joinOrganization: 'You have joined the organization successfully',
        leaveOrganization: 'You have left the organization successfully'
    }
}